M48
; DRILL file {KiCad 8.0.8} date 2025-10-05T09:32:34-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-05T09:32:34-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.400
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.180
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.550
%
G90
G05
T1
X112.11Y-55.5
T2
X48.4Y-38.0
X103.6Y-38.0
T3
X48.4Y-55.5
X103.6Y-20.5
M30
